branches:
  only:
    - master

language: node_js

node_js:
  - "$(jq -r '.engines.node' package.json)"

services:
  - redis-server

notifications:
  email: false

before_install:
  - npm install -g npm@"$(jq -r '.engines.npm' package.json)"

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test